### ISSUE TITLE
Use default system fonts to address remote font issues

### ISSUE THREAD

**Issue by jorgegonzalez** [raft-tech/django-admin-508#2]
Need to tweak the default font overrides in this module:

```css
body {
  font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;
}
```
